### ISSUE TITLE
Logout does not clear the Shibboleth cookie

### ISSUE THREAD

**Issue by yoonlees** [IllinoisSocialMediaMacroscope/CUPHD-Health-Status-Tool#1]
Logout link correctly redirect to the logout page but the user can still access the page without the shib auth. 

I'm not sure if this will work:
> from flask import session
> session.clear()

**Comment by longshuicy** [comment]
Hi @yoonlees 
After logout, I think the session is already cleared? If you try to refresh you will get an error:
![image](https://user-images.githubusercontent.com/13950475/90033094-b1807100-dc84-11ea-9fe7-72ec5a428eee.png)

And if you try to access the main page, you'll be redirect to shibboleth.

But do you mean you don't want user to access the /logout endpoint at all? Then maybe I can redirect to main page then it will point to shibboleth login again?
